### ISSUE TITLE
Rキーを押しても反応がない

### ISSUE THREAD

**Issue by Kirea413** [KoharuYuzuki/RecBoard#1]
上下キーは反応します
キーボードの入力も問題ないです。
PC:MacbookAir 2017年モデル
Arm版とも間違えていないです。

**Comment by KoharuYuzuki** [comment]
macOS版のzipファイルに起動コマンドファイル等が含まれていませんでした。
現在は修正したzipファイルに差し替えてあります。
"launch.command" ファイルをダブルクリックして起動してみてください。

**Comment by Kirea413** [comment]
> macOS版のzipファイルに起動コマンドファイル等が含まれていませんでした。 現在は修正したzipファイルに差し替えてあります。 "launch.command" ファイルをダブルクリックして起動してみてください。

@KoharuYuzuki 
 確認したら、ファイルは生成されているのですが音が全く入っていませんでした。
Macの設定もあっていて、アプリを再起動しても音がないです。
ちゃんと起動はlaunch.commandを使いました。

**Comment by KoharuYuzuki** [comment]
設定 -> セキュリティとプライバシー -> マイク でRecBoardがONになっているでしょうか？
また、生成されたファイルのサイズは何バイトでしょうか？

**Comment by minato413** [comment]
> 設定 -> セキュリティとプライバシー -> マイク でRecBoardがONになっているでしょうか？ また、生成されたファイルのサイズは何バイトでしょうか？

Rキーを押した長さによって変わります(zipファイル参照)
[音声ファイル.zip](https://github.com/KoharuYuzuki/RecBoard/files/12783026/default.zip)

また設定のマイクのところにそもそもなかったです(スクリーンヨット参照)
![スクリーンショット 2023-10-02 午後10 26 07](https://github.com/KoharuYuzuki/RecBoard/assets/109840302/1dfaad09-1344-4c3a-8aab-dec7e5a7ff1b)

**Comment by Kirea413** [comment]
> 設定 -> セキュリティとプライバシー -> マイク でRecBoardがONになっているでしょうか？
また、生成されたファイルのサイズは何バイトでしょうか？

@KoharuYuzuki 
設定には何もなかったです(スクリーンショット参照)
![スクリーンショット 2023-10-02 午後10 34 12](https://github.com/KoharuYuzuki/RecBoard/assets/109840302/1ced8949-ffe7-4ef1-b926-b666845c4951)

音声ファイルのサイズは長さによって変わっています...(zipファイル参照)
[音声ファイル.zip](https://github.com/KoharuYuzuki/RecBoard/files/12783070/default.zip)

**Comment by Kirea413** [comment]
マイクの設定もちゃんと内臓マイクにしています。

**Comment by KoharuYuzuki** [comment]
先程リリースしたv1.1.1でマイクへのアクセス権限を要求するダイアログが出るようになっていると思います。
https://github.com/KoharuYuzuki/RecBoard/releases/tag/v1.1.1

**Comment by Kirea413** [comment]
> 先程リリースしたv1.1.1でマイクへのアクセス権限を要求するダイアログが出るようになっていると思います。 https://github.com/KoharuYuzuki/RecBoard/releases/tag/v1.1.1

改善されました、ありがとうございます！
