### ISSUE TITLE
Windows11(x64)で、録音が不可能

### ISSUE THREAD

**Issue by Kirea413** [KoharuYuzuki/RecBoard#2]
Rキーを離すと、以下の画像のようなウィンドウが出ます。
![image](https://github.com/user-attachments/assets/b7888b87-cea8-44d0-b60c-9f7638d98890)

**Comment by KoharuYuzuki** [comment]
一応確認させてください。
ffmpegのパスは通してありますか？

**Comment by Kirea413** [comment]
通してある...と思ったらディレクトリの名前をタイプミスしてました...
初歩的なミスでIssues立ててすいません...
